### ISSUE TITLE
CPUInfos Object has no items methods.

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNMan#124]

**Comment by rowleya** [comment]
Is it meant to?

**Comment by Christian-B** [comment]
AbstractSpinnakerBase._recover_from_error calls
Transceiver._txrx.get_cores_not_in_state
which returns an CPUInfo object

it then does a iteritems over the  CPUInfo object
yet  CPUInfo object has neither
iteritems for python2
not items for python 3

**Comment by rowleya** [comment]
This isn't a bug in CPUInfo though - the bug is in its use.  Looking at the function though, it seems to return a CPUInfos item, which I believe does at least have the correct items for Python 2 (I can't say for sure on Python 3).

**Comment by Christian-B** [comment]
Ah yes its an  CPUInfos Object so the fix is easy

**Comment by Christian-B** [comment]
Pr for fix coming
