### ISSUE TITLE
send_scp_request_to

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNMan#147]
Full path to where you find the problem:
C:\Users\alan\Documents\software\SpiNNMan\spinnman\connections\udp_packet_connections\scamp_connection.py

What is the problem you see?
send_scp_request_to is never used

What do you think it should do instead?
go bye bye

What version of our software are you using?
master

**Comment by dkfellows** [comment]
I concur. This is unused.
