### ISSUE TITLE
redundant code

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNMan#149]
Full path to where you find the problem:
C:\Users\alan\Documents\software\SpiNNMan\spinnman\transceiver.py

What is the problem you see?
        # update the SCAMP connections replacing any x and y with the default
        # SCP request params with the boot chip coordinates
        for sc in self._scamp_connections:
            if (sc.chip_x == AbstractSCPRequest.DEFAULT_DEST_X_COORD
                    and sc.chip_y == AbstractSCPRequest.DEFAULT_DEST_Y_COORD):
                sc.update_chip_coordinates(
                    self._machine.boot_x, self._machine.boot_y)

What do you think it should do instead?
 Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.

What version of our software are you using?
master

**Comment by andrewgait** [comment]
Looks like this has been dealt with.
