### ISSUE TITLE
Initialization of the transceiver

### ISSUE THREAD

**Issue by sergiodavies** [SpiNNakerManchester/SpiNNMan#27]
if the Transceiver is initialized with no connections, the set of connections to not shut down is generated after a None, which throws an error.
Moreover, if no connections to a SpiNNaker board are made, discover_scamp_connections should terminate immediately, but the check on the _sending_connections is for None rather than an empty dictionary.

**Comment by Christian-B** [comment]
Code has moved on so much this is was opened. Assuming not longer a problem.
