### ISSUE TITLE
quick_tests broken

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNMan#276]
I notice that quick_tests.py currently do not work.

problem 1.
"Accessing config values before setup is not supported"

fix:
from spinnman.config_setup import unittest_setup
...
unittest_setup()

problem 2.
No such file or directory: 'hello.aplx'

possible fix:
There is a hello.c but no make to build it

**Comment by rowleya** [comment]
I think hello.aplx can be made using the "standard" makefile in spinnaker_tools e.g. ```make -f $SPINN_DIRS/make/app.make APP=hello```.
