### ISSUE TITLE
Initialization of a discovery transceiver

### ISSUE THREAD

**Issue by sergiodavies** [SpiNNakerManchester/SpiNNMan#28]
If a transceiver is initialised with discover=True, there is an unchecked assumption that the board has been booted.
In case this assumption is not true, the initialization of the Transceiver terminates with an error in the communication with the board through SCP messages

**Comment by alan-stokes** [comment]
The current code base for spinnman no longer has discover as a parameter, and does not assume the machine is even powered on, yet alone booted. So I think the changes from multi-board boot, spinnman speed up and others have inadvertently made this issue go away.

therefore closing the issue.
