### ISSUE TITLE
SpiNNaker comms requirements

### ISSUE THREAD

**Issue by mossblaser** [SpiNNakerManchester/SpiNNMan#3]
This issue is an attempt to assemble a set of requirements for the SpiNNaker communication facilities implemented by SpiNNMan, covering all cases of communication with SpiNNaker and a host. This issue was created to help formalise the ideas discussed this morning with @alan-stokes @rowleya.

Key desired functionality:
- Booting of machine
- Querying of machine state
  - What cores exist?
  - What (internal) links exist?
  - What peripherals exist?
  - What external links to the host exist (e.g. ethernet, S-ATA)
  - Is it booted?
  - What is running and where?
  - What's in IOBUFs?
  - How many cores are in a given state (e.g. SYNC0 ?)
  - What are the current router stat counter values?
  - What routing table entries are installed?
- Loading of application binaries
- Sending signals to applications
- Loading/retrieving data to/from SDRAM
- Injecting/extracting (possibly arbitrary) SpiNNaker packets:
  - At low rates (e.g. simple  application-defined control mechanisms, e.g. retina on/off)
  - At high rates (e.g. realtime stuff)
- Sending/receiving arbitrary SDP packets (including SCP)

Clearly some functionality will depend on hardware used (e.g. very high bandwidth I/O) and for unsupported features on certain platforms, either degraded performance or `NotImplemented` exceptions should result.

Other requirements:
- Interface presented should be identical independent of hardware interface used (to the maximum extent possible)
- Sensible default assumptions should be made about what links are used for what when more than one is present, advanced users should be able to cleanly override these.
- Multiple links into a single SpiNNaker system should be possible
- Multiple types of links should be available (simultaneously) e.g. Ethernet, S-ATA
- If multiple independent SpiNNaker machines are connected to a PC, the software should not interfere between them so that completely separate tasks can be executed.
- When loading data into SDRAM in particular, multiple links should be used (ideally automatically) where possible to improve overall loading performance.

Please submit anything you feel is missing from this list!

**Comment by alan-stokes** [comment]
just a wrap up. apart from identifiying peripherals. Everything on that list is done.

**Comment by alan-stokes** [comment]
identifiying peripherals impossible to do in general. therefore this issue can be closed.
