### ISSUE TITLE
Transceiver seems to be missing fill command

### ISSUE THREAD

**Issue by neworderofjamie** [SpiNNakerManchester/SpiNNMan#59]
It's very useful to be able to zero buffers when they're allocated e.g. https://github.com/project-rig/rig/blob/master/rig/machine_control/machine_controller.py#L1020

**Comment by rowleya** [comment]
This has been added to #58 now - the MemoryIO also supports this command:
```
memory = MemoryIO(...)
memory.fill(0x12345678)
memory.fill(0xFF, data_type=FillDataType.BYTE)
```

**Comment by andrewgait** [comment]
Referenced PR has been merged, so closing this issue.
