### ISSUE TITLE
SpinnakerBootMessages holds open file handle

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/SpiNNMan#73]
There's no reason for the `SpinnakerBootMessages` class in `spinnman/messages/spinnaker_boot/spinnaker_boot_messages.py` to hold an open file handle; the data it is holding onto that way is just around 27kB. Reading it into a string and then just using that would work at least as well, and wouldn't leak an OS resource (at a cost of a tiny amount more memory).

**Comment by rowleya** [comment]
Fixed in #86

**Comment by alan-stokes** [comment]
fixed in master
