### ISSUE TITLE
Request for disabling machine watchdog timers in config file

### ISSUE THREAD

**Issue by rjames91** [SpiNNakerManchester/SpiNNMan#87]
Instead of modifying software_watchdog_count in system_variables_boot_values.py it would be ideal to be able to disable the watchdog timer from a config file. By creating this functionality the SpiNNakEar branch can be deleted from this repository.

**Comment by alan-stokes** [comment]
this is currently supported by spinnman master. closing issue

**Comment by rowleya** [comment]
Added SpiNNakerManchester/SpiNNFrontEndCommon#260 in place of this
